version: '3'
services:
  db:
    build: .
    image: jordanskomer/serverless
    environment:
      ROOT: db
    ports:
      - 8000:8000
    restart: always
  serverless:
    build:
      context: .
    image: jordanskomer/serverless
    ports:
      - 3000:3000
    command: serverless offline start
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - ./package.json:/usr/src/app/package.json