version: '3'
services:
  db:
    image: jordanskomer/serverless-dynamodb
    command: sls dynamodb start
    ports:
      - 8000:8000
    restart: always
  serverless:
    image: jordanskomer/serverless
    ports:
      - 3000:3000
    command: sls offline start
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - ./package.json:/usr/src/app/package.json