version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./.docker/db.Dockerfile
    image: kohkane/db
    ports:
      - 8000:8000
    restart: always
  serverless:
    build:
      context: .
      dockerfile: ./.docker/functions.Dockerfile
    image: kohkane/functions
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - ./package.json:/usr/src/app/package.json