service:
  name: base

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: '3000'
    host: '0.0.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  profile: kohkane_serverless
  stage: ${opt:stage, 'dev'}
  tracing: true
  apiName: api.kohkane.com
  deploymentBucket:
    name: com.kohkane.deploys
    serverSideEncryption: AES256
  apiKeys:
    - ${self:provider.stage}-key
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::stashes.kohkane.com"
        - "arn:aws:s3:::stashes.kohkane.com/*"
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
       Resource: "arn:aws:s3:::com.kohkane.deploy"
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
       Resource: "arn:aws:s3:::com.kohkane.deploy/*"

package:
  include:
    - users/**
  exclude:
    - .git/**
    - .circleci/**
    - users/.test/**

functions:
  # - ${file(./users/function.yml)}
  - ${file(./projects/function.yml)}

# resources:
#   Resources:
#     pathmapping:
#       Type: AWS::ApiGateway::BasePathMapping
#       Properties:
#         BasePath: dev
#         DomainName: api.kohkane.com
#         RestApiId:
#           Ref: ApiGatewayRestApi
#         Stage: dev

